### ISSUE TITLE
My TODO list

### ISSUE THREAD

**Issue by FurkanS1821** [LeagueSandbox/GameServer#235]
- [ ] 1. Implement laser spells

- [ ] 2. Implement targeted AoE

- [ ] 3. Add buffs, shields, crowd control and invulnerability

- [ ] 4. Make turrets/inhibitors/nexus invulnerable if next turret is alive

- [ ] 5. Get how to make things untargetable

- [ ] 6. Implement untargetability

Somewhere between:

- [ ] Implement pausing game when you get pause packet's structure

**Comment by FurkanS1821** [comment]
Seperated this into issues, this is unnecessary atm
